name: base_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^3.3.1
  dbcrypt: ^2.0.0
  dotenv: ^4.2.0
  mysql1: ^0.20.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

  commons_core:
    path: ./packages/commons/commons_core
